#!/bin/bash

exec 3>&1 1>&2
trap 'echo "${BASH_SOURCE[0]##*/}: Error $? (l.$LINENO) - aborted."; exit 1;' ERR

[[ $CHECK_BUILD == "pass" ]]
[[ $CHECK_URL == "pass" ]]

cat >&3 << EOF

## Build is reproducible

### Package
*$DEB_PACKAGE*

### Version
*$DEB_VERSION*

### Download

[$DEB_URL]($DEB_URL)

Integrity checked as of: *$CHECK_URL_LAST*

### Metadata

\`\`\`

EOF

cat >&3 "$DEB_INFO"

cat >&3 << EOF
\`\`\`

> [!TIP]
> Download and verify package integrity by sourcing the metadata snippet above and:
> \`\`\`
> wget -nc -P /tmp "\$DEB_URL" && sha256sum -c <<< "\$DEB_SHA256 /tmp/\${DEB_URL##*/}"
> \`\`\`
>
> Install the downloaded package:
> \`\`\`
> apt install /tmp/\${DEB_URL##*/}
> \`\`\`

EOF
