#!/bin/bash
set -e

case "$1" in
    configure)

		no-subscription -a || echo "ISSUES reported: $1" >&2
		no-nag -a || echo "ISSUES reported: $1" >&2

    ;;

    triggered)

        for t in $2; do

            case "$t" in

                "/etc/apt/sources.list.d/pve-enterprise.list"|\
                "/etc/apt/sources.list.d/pbs-enterprise.list"|\
                "/etc/apt/sources.list.d/pmg-enterprise.list")

                    no-subscription -at "$t" || echo "ISSUES reported: $1 $2" >&2

                ;;

                "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"|\
                "/usr/share/pve-manager/js/pvemanagerlib.js"|\
                "/usr/share/javascript/proxmox-backup/js/proxmox-backup-gui.js"|\
                "/usr/share/javascript/pmg-gui/js/pmgmanagerlib.js")

                    no-nag -at "$t" || echo "ISSUES reported: $1 $2" >&2

                ;;

            esac

        done

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *) 
        echo "ERROR: $0 - unknown argument: $1" >&2
        exit 1
    ;;
esac