#!/bin/bash
set -e

pvelist="/etc/apt/sources.list.d/pve-enterprise.list"
pbslist="/etc/apt/sources.list.d/pbs-enterprise.list"
proxmoxlib="/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"

case "$1" in
    configure)
		free-pmx-no-subscription auto-configure || echo "ISSUES reported: $1" >&2
		free-pmx-no-nag auto-configure || echo "ISSUES reported: $1" >&2
    ;;

    triggered)
		case "$2" in
			"$pvelist")
				free-pmx-no-subscription auto-triggered-pve || echo "ISSUES reported: $1 $2" >&2
			;;
			"$pbslist")
				free-pmx-no-subscription auto-triggered-pbs || echo "ISSUES reported: $1 $2" >&2
			;;
			"$proxmoxlib")
				free-pmx-no-nag auto-triggered || echo "ISSUES reported: $1 $2" >&2
			;;
		esac
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "ERROR: $0 - unknown argument: $1" >&2
        exit 1
    ;;
esac